import './globals.scss'
import { Poppins } from 'next/font/google'
import Head from 'next/head'

const poppins = Poppins({ subsets: ['latin'], weight: ["300"] })
export const metadata = {
  title: 'Bespoke',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'></link>
      </Head>
      <body className={poppins.className}>
        {children}
      </body>
    </html>
  )
}
